# Generated by Django 4.0.3 on 2022-03-16 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='expectedPrice',
        ),
    ]
