# Generated by Django 4.0.3 on 2022-03-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_date_auctionlisting_expectedprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
