# Generated by Django 4.0.3 on 2022-03-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='expectedPrice',
            new_name='startingBid',
        ),
    ]
