# Generated by Django 4.0.3 on 2022-03-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_expectedprice_auctionlisting_startingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
