# Generated by Django 4.0.3 on 2022-03-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlisting_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageURL',
            field=models.URLField(blank=True, default='/static//auctions/images/noImageIcon.png', null=True),
        ),
    ]
