# Generated by Django 4.0.3 on 2022-03-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auctionlisting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageURL',
            field=models.CharField(blank=True, default='/static//auctions/images/noImageIcon.png', max_length=255),
        ),
    ]
