# Generated by Django 4.0.3 on 2022-03-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_comment_bid_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='highestBidID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
