# Generated by Django 4.0.3 on 2022-03-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctionlisting_highestbidid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item',
            new_name='listingId',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listing',
            new_name='listingId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='userId',
        ),
    ]
