# Generated by Django 4.0.3 on 2022-03-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_item_bid_listingid_rename_user_bid_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='highestBidID',
            new_name='highestBidId',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='listingId',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listingId',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userId',
            new_name='user',
        ),
    ]
