# Generated by Django 4.0.3 on 2022-03-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_rename_highestbidid_auctionlisting_highestbidid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
