# Generated by Django 4.0.3 on 2022-03-17 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auctionlisting_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='usersWatching',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
